# treefmt-nix configuration. Run via `nix fmt` / `just codemod-fmt` (write
# mode); `just lint-fmt` builds the read-only `checks.conformist` derivation.
# treefmt-nix resolves each formatter binary and emits the config file that the
# conformist runner consumes (see flake.nix's treefmtEval / conformistConfig).
{ lib, ... }:
{
  projectRootFile = "flake.nix";

  # Go: goimports (import grouping) runs first, then gofumpt re-canonicalizes
  # the result. Lower priority runs earlier. Mirrors the old Taskfile `fmt`
  # task (gofumpt -w .) plus the .golangci.yml goimports formatter.
  programs.goimports.enable = true;
  settings.formatter.goimports.priority = 1;
  programs.gofumpt.enable = true;
  settings.formatter.gofumpt.priority = 2;

  programs.nixfmt.enable = true;

  # Shell scripts (e.g. scripts/run-labeler.sh): 2-space indent, simplify,
  # case-indent. Scoped to *.sh / *.bash so it never reaches for unrelated
  # shell-ish files.
  programs.shfmt.enable = true;
  settings.formatter.shfmt.includes = lib.mkForce [
    "*.sh"
    "*.bash"
  ];
  settings.formatter.shfmt.options = lib.mkForce [
    "-i"
    "2"
    "-s"
    "-ci"
  ];

  # The stats dashboard's HTML/CSS/JS — the old Taskfile `fmt:html` task ran
  # prettier over exactly these. Scoped to script extensions so prettier does
  # not reach for JSON / YAML / markdown elsewhere in the tree.
  programs.prettier.enable = true;
  settings.formatter.prettier.includes = lib.mkForce [
    "internal/cmd/stats/index.html"
    "internal/cmd/stats/index.css"
    "internal/cmd/stats/index.js"
  ];

  settings.global.excludes = [
    # Lockfiles / generated manifests — owned by their generators.
    "flake.lock"
    "go.mod"
    "go.sum"
    "gomod2nix.toml"
    # Generated by their respective codegen lanes (just sqlc / swag / schema).
    "internal/db/*.sql.go"
    "internal/swagger/**"
    "schema.json"
    # Large binary/vector assets.
    "*.svg"
    # Non-source / docs.
    "*.md"
    "LICENSE.md"
    "CLA.md"
    "sweatfile"
    "result"
    "result-*"
    ".tmp/**"
    ".direnv/**"
  ];
}
